"""Initial migration - create hives table

Revision ID: 9626a4922768
Revises: 
Create Date: 2025-02-16 21:26:42.040442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9626a4922768'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_lng', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_index('UK16pelyplvg4vx6td27obgieen')

    op.drop_table('followers')
    op.drop_table('comments')
    op.drop_table('_user')
    op.drop_table('login_attempts')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_post_created_at')
        batch_op.drop_index('idx_post_user')
        batch_op.drop_index('idx_post_user_created')

    op.drop_table('posts')
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index('UK2jovqhqo324cubdomovkex03b')

    op.drop_table('likes')
    op.drop_table('user_profiles')
    with op.batch_alter_table('user_relationships', schema=None) as batch_op:
        batch_op.drop_index('UKlvt3ocg4aqvo1s3x9hwc3thrs')
        batch_op.drop_index('idx_relationship_follower')
        batch_op.drop_index('idx_relationship_following')
        batch_op.drop_index('idx_relationship_status')

    op.drop_table('user_relationships')
    op.drop_table('_user_seq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_user_seq',
    sa.Column('next_val', mysql.BIGINT(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_relationships',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_blocked', mysql.BIT(length=1), nullable=False),
    sa.Column('is_close', mysql.BIT(length=1), nullable=False),
    sa.Column('is_muted', mysql.BIT(length=1), nullable=False),
    sa.Column('notification_preference', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.ENUM('ACCEPTED', 'BLOCKED', 'PENDING'), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['_user.id'], name='FK5lcq7vsbdofooji9q91n185y0'),
    sa.ForeignKeyConstraint(['following_id'], ['_user.id'], name='FKgnam058ban9a2cb9wass2dyap'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_relationships', schema=None) as batch_op:
        batch_op.create_index('idx_relationship_status', ['follower_id', 'following_id', 'status', 'is_blocked'], unique=False)
        batch_op.create_index('idx_relationship_following', ['following_id'], unique=False)
        batch_op.create_index('idx_relationship_follower', ['follower_id'], unique=False)
        batch_op.create_index('UKlvt3ocg4aqvo1s3x9hwc3thrs', ['follower_id', 'following_id'], unique=True)

    op.create_table('user_profiles',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bio', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profile_picture_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('website', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['_user.id'], name='FKawta2ag0ha0kpo50hih14ptxb'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('likes',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('post_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='FKry8tnr4x2vwemv2bb0h5hyl0x'),
    sa.ForeignKeyConstraint(['user_id'], ['_user.id'], name='FKpsk1l358f7k2fb1wej247ts0i'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index('UK2jovqhqo324cubdomovkex03b', ['user_id', 'post_id'], unique=True)

    op.create_table('posts',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('caption', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('media_type', mysql.ENUM('IMAGE', 'VIDEO'), nullable=True),
    sa.Column('media_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['_user.id'], name='FKfeyahhljdty467fx2801oco30'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_post_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_post_user', ['user_id'], unique=False)
        batch_op.create_index('idx_post_created_at', ['created_at'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('attempt_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('success', mysql.BIT(length=1), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['_user.id'], name='FKc8l6h1fj419g2o1be587ekult'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('_user',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('firstname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lastname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.ENUM('ADMIN', 'MANAGER', 'USER'), nullable=True),
    sa.Column('bio', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profile_picture_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('website', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comments',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('post_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='FKh4c7lvsc298whoyd4w9ta25cr'),
    sa.ForeignKeyConstraint(['user_id'], ['_user.id'], name='FKi5d1g4lt0mw88wnfqfexhae7e'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('followers',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['_user.id'], name='FKo2fevyupentvmrx51drqm2b21'),
    sa.ForeignKeyConstraint(['following_id'], ['_user.id'], name='FKkrb5mg98p3224wblf33mm6ojg'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_index('UK16pelyplvg4vx6td27obgieen', ['follower_id', 'following_id'], unique=True)

    op.drop_table('hives')
    # ### end Alembic commands ###
